# Generated by Django 5.2 on 2025-05-05 21:36

import django.db.models.deletion
import portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('ip_address', models.CharField(max_length=255, validators=[portal.models.validate_ip_or_url])),
                ('api_key', models.CharField(max_length=32)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ping', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portal_printers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ip_address', 'api_key')},
            },
        ),
    ]
