# Generated by Django 4.1.4 on 2023-01-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='ping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
