# Generated by Django 4.1.4 on 2023-06-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprint',
            name='printer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.printer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.profile'),
        ),
    ]
