# Generated by Django 4.1.4 on 2023-07-26 12:54

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_printer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='ip_address',
            field=models.CharField(max_length=255, validators=[portal.models.validate_ip_or_url]),
        ),
    ]
