# Generated by Django 3.2.25 on 2025-05-05 19:47

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_migrate_profile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('ip_address', models.CharField(max_length=255, validators=[core.validators.validate_ip_or_url])),
                ('api_key', models.CharField(max_length=32)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ping', models.BooleanField(default=False)),
                ('printing', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'unique_together': {('ip_address', 'api_key')},
            },
        ),
    ]
