trigger:
- main

pool: 
 vmImage: 'ubuntu-20.04'

variables:
 imageName: 'printai'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  inputs:
    script: 'docker image prune -f' 

- task: Docker@2
  displayName: 'Build image'
  inputs:
    containerRegistry: 'PrintAI Container Registry'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'